### ISSUE TITLE
RFC-6838: parameter should not be specified more than once

### ISSUE THREAD

**Issue by g4s8** [g4s8/mime#3]
According to [Parameter Requirements](https://tools.ietf.org/html/rfc6838#page-13):
> It is an error for a specific parameter to be specified more than once.

So lets change `params()` signature of `MimeType` from `Map<String, List<String>>` to 
`Map<String, String>`. If parameter specified more than once `params()` should throw an exception.

**Comment by Viciouss** [comment]
Hi, I'd like to work on this. Is an IllegalStateException okay for this purpose?

**Comment by g4s8** [comment]
Hi @Viciouss! Thanks for contributing. I'll look at your PR soon. About exception: it would be better to use checked one here, you can take `IOException` or another extended from `IOException`.

**Comment by 0crat** [comment]
Oops! Job `gh:g4s8/mime#3` was not in scope

**Comment by g4s8** [comment]
@Viciouss thanks!

**Comment by g4s8** [comment]
@rultor release, tag=`0.2`
